### ISSUE TITLE
Website Unavailable

### ISSUE THREAD

**Issue by eIects** [kavispires/line-distribution-app#113]
When I sign in with my Google account, it just constantly loads and never stops loading. This is the only Line Distribution maker I can find on the internet, kind of sad it doesn't work.

**Comment by kavispires** [comment]
This was a personal project done during my free time using a paid firebase server. When someone got a hold of this and people were trying to log in, I panicked and locked the database since it was consumer-ready (it was kinda never meant to be) and I can't afford $$$ having users.
